#!/usr/bin/env python
# coding: utf-8

# In[1]:


# Imprimir los primeros 10 números naturales
for i in range(1, 11):
    print(i)


# In[3]:


# Imprimir los primeros 10 números impares
for i in range(1, 20, 2):
    print(i)


# In[5]:


# Imprimir los primeros 10 números naturales en orden descendente
for i in range(10, 0, -1):
    print(i)


# In[9]:


# Capturar el número para la tabla de multiplicar
numero = int(input("Ingresa el número para la tabla de multiplicar: "))

# Imprimir la tabla de multiplicar
for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}")


# In[11]:


# Capturar el número
numero = int(input("Ingresa un número: "))

# Inicializar el producto
producto = 1

# Multiplicar los dígitos del número
while numero > 0:
    digito = numero % 10
    producto *= digito
    numero //= 10

# Imprimir el producto de los dígitos
print(f"El producto de los dígitos es: {producto}")


# In[ ]:




