#!/usr/bin/env python
# coding: utf-8

# In[1]:


#-------------------------------------------------------------------------#
# Crear una tuple con 3 elementos: 10, "Hola" y 3.14
tupla = (10, "Hola", 3.14)
print(tupla)

#-------------------------------------------------------------------------#
# La tupla (1,2,3,4,5), accede y escribe el tercer elemento
tupla = (1, 2, 3, 4, 5)
print(tupla[2])  # El tercer elemento tiene índice 2

#-------------------------------------------------------------------------#
# Concatena las tuplas y almacena el resultado en una tupla nueva
tupla1 = (1, 2, 3)
tupla2 = (4, 5, 6)
tupla_final = tupla1 + tupla2
print(tupla_final)

#-------------------------------------------------------------------------#
# Desempaqueta la tupla en tres variables y escribe sus valores
tupla = ('a', 'b', 'c')
var1, var2, var3 = tupla
print(var1, var2, var3)

#-------------------------------------------------------------------------#
# Verifica si el elemento 7 existe en la tupla (1,3,5,7,9)
tupla = (1, 3, 5, 7, 9)
existe = 7 in tupla
print(existe)

#-------------------------------------------------------------------------#
# Crea una tupla (0,1,2,3,4,5) y escribe los elementos del índice 2 a 4 con slice
tupla = (0, 1, 2, 3, 4, 5)
resultado = tupla[2:5]
print(resultado)

#-------------------------------------------------------------------------#
# Encuentra la longitud de una tupla (10,20,30,40,50)
tupla = (10, 20, 30, 40, 50)
length = len(tupla)
print(length)

#-------------------------------------------------------------------------#
# Crea una tupla y repítela 3 veces
tupla = (1, 2, 3)
resultado = tupla * 3
print(resultado)

#-------------------------------------------------------------------------#
# Convierte la lista [1, 2, 3] a tupla
lista = [1, 2, 3]
tupla = tuple(lista)
print(tupla)

#-------------------------------------------------------------------------#
# Encuentra los valores mínimo y máximo de la tupla (5,12,3,8,15)
tupla = (5, 12, 3, 8, 15)
valor_minimo = min(tupla)
valor_maximo = max(tupla)
print('Mínimo:', valor_minimo, 'Máximo:', valor_maximo)


# In[ ]:




