#!/usr/bin/env python
# coding: utf-8

# In[1]:


# Conversor de divisas

# Tasas de conversión (1 peso mexicano a otras monedas)
yuan = 2.81
yen = 0.14
dolar = 20.49
euro = 21.28
libra = 25.5

# Solicitar cantidad en pesos
pesos = float(input("Ingresa la cantidad de pesos a convertir: "))

# Realizar conversiones
print("Los pesos equivalen a:")
print(f"{pesos / yuan:.2f} yuanes")
print(f"{pesos / yen:.2f} yenes")
print(f"{pesos / dolar:.2f} dólares")
print(f"{pesos / euro:.2f} euros")
print(f"{pesos / libra:.2f} libras esterlinas")



# In[ ]:




